### ISSUE TITLE
Typo in client middleware filename

### ISSUE THREAD

**Issue by lamartire** [ya-kostik/redbone#6]
`getServerDispatchMidddleware` --> `getServerDispatchMiddleware`
I think we should fix this. It's not critical, but not right too :smile_cat:

**Comment by ya-kostik** [comment]
I think we can fix it at v1.1.0

PR are welcome.

**Comment by ya-kostik** [comment]
Fixed at [this commit](https://github.com/ya-kostik/redbone/commit/bc73f28c7bad231c489222348ae464928f7c4975)
